### ISSUE TITLE
Getting PostCSS plugin error:  "[object Object] is not a PostCSS plugin"

### ISSUE THREAD

**Issue by jnmandal** [TryGhost/Casper#737]
This could be my naivete but I cannot seem to get the dependencies straigtened out here. When booting up to use `dev`, I get this error:

```
yarn run v1.22.5
warning casper@3.1.0: The engine "ghost" appears to be invalid.
warning casper@3.1.0: The engine "ghost-api" appears to be invalid.
$ gulp
[17:10:22] Using gulpfile ~/Development/Casper/gulpfile.js
[17:10:22] Starting 'default'...
[17:10:22] Starting 'css'...
[17:10:22] 'css' errored after 20 ms
[17:10:22] Error in plugin "gulp-postcss"
Message:
    [object Object] is not a PostCSS plugin
Details:
    fileName: /Users/jnmandal/Development/Casper/assets/css/global.css

Stack:
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/Users/jnmandal/Development/Casper/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/Users/jnmandal/Development/Casper/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/Users/jnmandal/Development/Casper/node_modules/postcss/lib/postcss.js:55:10)
    at /Users/jnmandal/Development/Casper/node_modules/gulp-postcss/index.js:50:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[17:10:22] 'default' errored after 22 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Screenshot

<img width="1018" alt="Screen Shot 2020-09-17 at 17 11 03" src="https://user-images.githubusercontent.com/7440196/93533634-fabd8380-f908-11ea-9539-524c3a4e07c7.png">

### Steps to Reproduce
 
 1. run `yarn install`
 2. run `yarn dev`

### Technical details

* Casper Version:  3.1.0
* Ghost Version: n/a
* Browser Version:  n/a
* OS Version: macOS 10.15.6
* nodejs: v12.18.4
* yarn: 1.22.5

**Comment by vikaspotluri123** [comment]
@jnmandal you can get around the issue by downgrading autoprefixer to 9.x (`yarn add autoprefixer@9.8.6 --dev`). The issue arises because of major architectural changes from Postcss 7 (Autoprefixer 9.x) and 8 (Autoprefixer 10.x)

**Comment by jnmandal** [comment]
That did it. Thanks!
